name: 'Graph Validator test'
description: 'TODO'
inputs:
  directory:
    description: 'Directory to parse'
    required: true
    default: '..'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: logseq-cldwalker/graph-validator
        ref: with-composite
        path: _graph-validator

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'
        cache-dependency-path: _graph-validator/yarn.lock

    - name: Fetch yarn deps
      run: cd _graph-validator && yarn install --immutable
      shell: bash

    - name: Run nbb tests
      run: cd _graph-validator && yarn test ${{ inputs.directory }}
      shell: bash
