name: 'Graph Validator test'
description: 'TODO'
inputs:
  directory:
    description: 'Directory to parse'
    required: true
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'
        cache-dependency-path: yarn.lock

    - name: Fetch yarn deps
      run: yarn install --immutable
      shell: bash

    - name: Run nbb tests
      run: yarn test ${{ inputs.directory }}
      shell: bash
