on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello world action step
        id: hello
        uses: logseq-cldwalker/graph-validator@with-composite
        # with:
        #   directory: '.'
