on: [push]

jobs:
  hello_world_job:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: logseq-cldwalker/graph-validator@with-composite
        # with:
        #   directory: '.'
